### ISSUE TITLE
Torchvision error when running code

### ISSUE THREAD

**Issue by LR32768** [paschalidoud/superquadric_parsing#2]
Hello, I am trying to apply your code for my project and I met some problems. I followed all the instructions provided by the README and create a separate environment.
But when I was running the code, such error appears
`Traceback (most recent call last):
  File "forward_pass.py", line 21, in <module>
    from learnable_primitives.common.dataset import get_dataset_type,\
  File "../learnable_primitives/common/dataset.py", line 6, in <module>
    from torchvision import transforms
  File "/usr/local/lib/python2.7/dist-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/usr/local/lib/python2.7/dist-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/usr/local/lib/python2.7/dist-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/usr/local/lib/python2.7/dist-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/usr/local/lib/python2.7/dist-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/usr/local/lib/python2.7/dist-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: /usr/local/lib/python2.7/dist-packages/torchvision/_C.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
`

I guess it is come torchvision incompatible problem, do you have any advice for solving it?
 THX

**Comment by LR32768** [comment]
Also, there is no instructions for how to specify the organization for my our mesh models so as to use your code, could you add it to the introduction please? Or I have to read your code and try to understand it, thanks
